version: '{branch}-1.0.{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Release
skip_commits:
  files:
    - '.gitignore'
    - '*.md'
before_build:
  - nuget restore
build:
  project: Maria.sln
  verbosity: minimal
before_package:
- ps: .\BuildUnityPackages.ps1
artifacts:
- path: '*.unitypackage'