version: '{branch}-{build}'

skip_tags: true

image: Visual Studio 2019
configuration: Release

environment:
  nodejs_version: 12
  GH_TOKEN:
    secure: OCJrZypxmjb/p7vZIcwiGR4SaMiHZ269r2vcgPKdf5E+bv86X7aW+doKKR7HcTgh

skip_commits:
  files:
    - '.gitignore'
    - '*.md'
    - 'docs/*'

before_build:
  - nuget restore
build:
  project: Maria.sln
  verbosity: minimal

before_package:
- ps: .\BuildUnityPackages.ps1

artifacts:
- path: '*.unitypackage'

cache: '%APPDATA%\npm'

install:
- ps: >-

    Install-Product node $env:nodejs_version



    npm install -g semantic-release


deploy_script:
- semantic-release