image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - export PROJECT_NAME=Maria.sln
          #- export TEST_NAME=yourTestName
          - dotnet restore
          - dotnet build $PROJECT_NAME
          #- dotnet test $TEST_NAME