name: Code coverage
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.github_token }}


